<script data-cfasync="false " src="../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.html"></script>
<script src="{{ asset('front') }}/js/vendor/modernizr-3.6.0.min.js"></script>
<script src="{{ asset('front') }}/js/vendor/jquery-3.6.0.min.js"></script>
<script src="{{ asset('front') }}/js/vendor/jquery-migrate-3.3.0.min.js"></script>
<script src="{{ asset('front') }}/js/vendor/bootstrap.bundle.min.js"></script>
<script src="{{ asset('front') }}/js/plugins/slick.js"></script>
<script src="{{ asset('front') }}/js/plugins/jquery.syotimer.min.js"></script>
<script src="{{ asset('front') }}/js/plugins/waypoints.js"></script>
<script src="{{ asset('front') }}/js/plugins/wow.js"></script>
<script src="{{ asset('front') }}/js/plugins/perfect-scrollbar.js"></script>
<script src="{{ asset('front') }}/js/plugins/magnific-popup.js"></script>
<script src="{{ asset('front') }}/js/plugins/select2.min.js"></script>
<script src="{{ asset('front') }}/js/plugins/counterup.js"></script>
<script src="{{ asset('front') }}/js/plugins/jquery.countdown.min.js"></script>
<script src="{{ asset('front') }}/js/plugins/images-loaded.js"></script>
<script src="{{ asset('front') }}/js/plugins/isotope.js"></script>
<script src="{{ asset('front') }}/js/plugins/scrollup.js"></script>
<script src="{{ asset('front') }}/js/plugins/jquery.vticker-min.js"></script>
<script src="{{ asset('front') }}/js/plugins/jquery.theia.sticky.js"></script>
<script src="{{ asset('front') }}/js/plugins/jquery.elevatezoom.js"></script>
<!-- Template  JS -->
<script src="{{ asset('front') }}/js/main8c94.js?v=4.1"></script>
<script src="{{ asset('front') }}/js/shop8c94.js?v=4.1"></script>
